name: CI

on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: [18]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up NodeJS ${{ matrix.node_version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node_version }}

      - name: Run CI
        run: |
          yarn install
          yarn lint
          yarn test
